### ISSUE TITLE
第一次打开，没有动画效果

### ISSUE THREAD

**Issue by sds0917** [hyjiacan/vue-slideout#1]
demo页面：https://hyjiacan.github.io/vue-slideout/

Top Right Bottom Left四个方向第一次打开，面板不是以滑动动画进入可视区域，而是以淡入效果进入可是区域。关闭再打开动画正常，便是滑动进入可是区域的。

**Comment by hyjiacan** [comment]
- 这不是BUG，只是写DEMO的时候并没有处理这个问题。
- 原因：在DEMO中，四个方向的显示我使用了同一个组件，只是修改了`dock`的值，此时组件内计算会出现这样的问题，在实际应用中不应该出现改变`dock`的值情形。
