### ISSUE TITLE
max-size to support x%

### ISSUE THREAD

**Issue by letitfly** [hyjiacan/vue-slideout#11]
In one of my website where I have to support both web and mobile, for example, I would like to use this way:
size: 600px
max-size: 100%

So that the slide out does not overflow when the screen is small.

**Comment by hyjiacan** [comment]
Slideout has limited the max value of `size` as `100%` (since _2.5.7_).

If the size specified is greater than `100%`, thus it **wouldn't work as expected**.

Here is a sample to make it  work:

```vue
<template>
  <slideout>
    <div class="wrapper">
      <div class="content">
      </div>
    </div>
  </slideout>
</template>

<style scoped>
.wrapper {
  width: 100%;
  height: 100%;
  overflow: auto;
}
.content {
  width: 600px;
}
</style>
```

**Comment by letitfly** [comment]
Thanks for your  quick reply! But I ended up using this and it seems working out fine.

.vue-slideout-layout {
    max-width: 100%;
 }

**Comment by hyjiacan** [comment]
> Thanks for your quick reply! But I ended up using this and it seems working out fine.
> 
> .vue-slideout-layout {
> max-width: 100%;
> }

:+1: I've write it the same way.
