### ISSUE TITLE
Is there a plan to eventually support Vue3?

### ISSUE THREAD

**Issue by dougalg** [hyjiacan/vue-slideout#12]
Do you have any plans to support Vue3 in the near future? This looks like a good project, but I want to make sure it will be forward compatible. Thanks for your hard work!

**Comment by hyjiacan** [comment]
Yes, there is. I am too busy on my work to do the migrating thing. It may be released after a few months.

**Comment by dougalg** [comment]
Awesome, thank you!

**Comment by hyjiacan** [comment]
Hi there, the 3.x release is available now.

```shell script
npm install @hyjiacan/vue-slideout@3.0.0
```

> The Slideout@3 used to work with Vue@3
