### ISSUE TITLE
this._removeKeyboardEvent is not a function?

### ISSUE THREAD

**Issue by dmhendricks** [hyjiacan/vue-slideout#13]
I'm a novice and I'm not sure how I could explain this in a reproducible way, but I figured it was worth asking anyway since I'm desperate. The component is working perfectly on the view/route that I have it on, but when I click to navigate to a different route, I get a fatal JavaScript error: `Uncaught (in promise) TypeError: this._removeKeyboardEvent is not a function
    at Proxy.beforeUnmount (slideout.common.js:3555)`

Has anyone else gotten this and figured out how to get around it? Am I missing some event handler?

I realize that it could be (and probably is) a problem with my app, but I thought I'd ask anyway in case it's a common error people experience. I tried adding handlers for the various events as well as a bunch of other things, but I still get it.

Thank you.

<img width="704" alt="Screen Shot 2021-09-09 at 3 12 05 PM" src="https://user-images.githubusercontent.com/8184361/132756225-909224df-cead-469e-87da-0c9c41324548.png">

<img width="389" alt="Screen Shot 2021-09-09 at 3 12 45 PM" src="https://user-images.githubusercontent.com/8184361/132756238-24c91a08-0422-4692-b5c1-6c46807cb37d.png">

**Comment by hyjiacan** [comment]
It's awkward =_-!  This is a **bug** over branch **master** (the 3.x version).  I will fix this and publish it in 30 minutes, keep your eyes on it please.
