### ISSUE TITLE
Slideout not showing

### ISSUE THREAD

**Issue by ZwiebelTVDE** [hyjiacan/vue-slideout#14]
Hello there, I used the samples on the README.md to get started in my project. 
Unfortunately nothing happens when I set visible to true. 
No Slideout and no output in the console. 
Is the sample broken or is the error on my side?

**Comment by hyjiacan** [comment]
> 

Show me you whole code pls.

**Comment by sadovsf** [comment]
Same issue here with minimal example being:
```vue
<script setup lang="ts">
    import Slideout from '@hyjiacan/vue-slideout';
    import '@hyjiacan/vue-slideout/dist/slideout.css';
    import { ref } from 'vue';

    const visible = ref(true);
</script>

<template>
    <Slideout
        v-model="visible"
        title="Test"
        dock="right"
        :show-mask="false"
        :resizable="true"
    >
        <div>
            Content test
        </div>
    </Slideout>
</template>
```

**Comment by sadovsf** [comment]
So from some more experiments it works when included globally which on the other hand adds bulk of data to whole app even though only single component needs it

**Comment by lucasoares** [comment]
Same here, but I'm unable to make it work even declaring it globally

**Comment by hyjiacan** [comment]
Which version of Vue you were working on ? The code above is for Vue3 only.

For Vue2, you should use `visible.sync="visible"` to make it work.

**Comment by sadovsf** [comment]
Vue3 with Composition API and typescript
