### ISSUE TITLE
the README example imports css from wrong location

### ISSUE THREAD

**Issue by iambumblehead** [hyjiacan/vue-slideout#16]
https://github.com/hyjiacan/vue-slideout/blob/master/README.md?plain=1#L75

The example in the README should import the css file from 'dist' rather than 'lib'
```diff
- import '@hyjiacan/vue-slideout/lib/slideout.css'
+ import '@hyjiacan/vue-slideout/dist/slideout.css'
```

**Comment by hyjiacan** [comment]
Got it! Thanks.
