### ISSUE TITLE
distance宽度问题

### ISSUE THREAD

**Issue by fefisher** [hyjiacan/vue-slideout#4]
这个distance能不能做成可变参数
![image](https://user-images.githubusercontent.com/12574463/61610812-bbf05700-ac8c-11e9-9e3e-3c6ecff9c265.png)

**Comment by hyjiacan** [comment]
这个功能就建议fork后自己修改了

**Comment by fefisher** [comment]
嗯嗯，这个还是挺好用的^_^^_^


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: hyjiacan <notifications@github.com>
发送时间: 2019年7月23日 09:34
收件人: hyjiacan/vue-slideout <vue-slideout@noreply.github.com>
抄送: chenng <1061863124@qq.com>, Author <author@noreply.github.com>
主题: 回复：[hyjiacan/vue-slideout] distance宽度问题 (#4)




这个功能就建议fork后自己修改了

**Comment by hyjiacan** [comment]
多谢支持
