### ISSUE TITLE
报这个..

### ISSUE THREAD

**Issue by edithTsang** [hyjiacan/vue-slideout#5]
[Vue warn]: Failed to resolve directive: scroll-lock

(found in <SlideOut>)

**Comment by hyjiacan** [comment]
哪个版本？简单点的处理方式：
```bash
npm i v-scroll-lock
```

**Comment by edithTsang** [comment]
> ？哪个版本简单点的处理方式：
> 
> ```shell
> npm i v-scroll-lock
> ```

我用的yarn add @hyjiacan/vue-slideout版本2.1.7 , 如果yarni v-scroll-lock的话是^1.0.1版本的.

**Comment by hyjiacan** [comment]
试试:
```javascript
import VScrollLock from 'v-scroll-lock'
Vue.use(VScrollLock)
```

参考: [v-scroll-lock](https://www.npmjs.com/package/v-scroll-lock)

**Comment by edithTsang** [comment]
好的谢谢. 这个组件挺好的

**Comment by hyjiacan** [comment]
> 好的谢谢. 这个组件挺好的

好像发现问题了，你先用上面的方法处理一下，有时间了才能更新

**Comment by edithTsang** [comment]
> 试试:
> 
> ```js
> import VScrollLock from 'v-scroll-lock'
> Vue.use(VScrollLock)
> ```
> 
> 参考: [v-scroll-lock](https://www.npmjs.com/package/v-scroll-lock)

试了也不行诶
