### ISSUE TITLE
Smoother Animation

### ISSUE THREAD

**Issue by jd1378** [hyjiacan/vue-slideout#7]
Hi !
Thanks for your work
Can you make this use transform and will-change property instead for smoother animation ?
It will help with the lag on low end mobile devices

**Comment by hyjiacan** [comment]
Happy to serve. I will try `will-change`.

**Comment by hyjiacan** [comment]
Feature added, see https://github.com/hyjiacan/vue-slideout/releases/tag/2.3.1

**Comment by jd1378** [comment]
Hi
Thanks for the effort but It's not working
(I don't know exactly how it works, but) I think you must open and close the slideout with transform (using translateX) and set will change for transform property for it to work ;)

**Comment by hyjiacan** [comment]
I did not use translateX, just position applied.  It seems that I need more time. :smile:

**Comment by hyjiacan** [comment]
Hi @jd1378 , thanks for your feedback, here are good news and bad news:
- Bad one, that I got no mobile dev skills. 
- Good one, I have push the newest code onto branch `dev`, could you pls take a test.

**Comment by jd1378** [comment]
Hi,
I just checked it out and it works nicely smooth , Thanks a lot for the hard work ! 👍
Also I just figured out that also my own page was lagging because of something else as well (only a handful of css 'filter' property was killing the page ...), so my bad, really sorry 😅😅😅
I'm sure the transform will help older browsers as well

**Comment by hyjiacan** [comment]
Great.  The feature will be available on npmjs at  next version.

**Comment by hyjiacan** [comment]
This feature now is available after tag [2.3.3](https://github.com/hyjiacan/vue-slideout/releases/tag/2.3.3)
