### ISSUE TITLE
how delete size  default 400px?

### ISSUE THREAD

**Issue by hizone** [hyjiacan/vue-slideout#9]
im use nuxtJS
the custom CLASS didnt work
and all my change in the new css class not good becuse the  heghit in default 400px and cant chnage that :/

**Comment by hyjiacan** [comment]
You  can specify default props  with 
```javascript
Vue.use(SlideOut, {
  // set props here
})
```

And, custom class takes  no  effective to  size prop.

**Comment by hizone** [comment]
thanks for help
u can give me exmple how to do that?
i didt whant to get 400px in y style on my html file

becuse i do that in my CSS files to be responsiv like i whant

**Comment by hyjiacan** [comment]
> thanks for help
> u can give me exmple how to do that?
> i didt whant to get 400px in y style on my html file
> 
> becuse i do that in my CSS files to be responsiv like i whant

I've add a `auto-size` faeature to support what you said. You can set `size` as `0` to enable this. 

see [Tag 2.3.5](https://github.com/hyjiacan/vue-slideout/releases/tag/2.3.5)
